import { useState } from 'react'
import { ArrowRight, Check, LockKeyhole, ShieldCheck } from 'lucide-react'

type Mode = 'welcome' | 'auth' | 'onboarding'

export default function EntryFlow({ mode }: { mode: Mode }) {
  const [step, setStep] = useState(0)
  const [email, setEmail] = useState('')
  const next = () => setStep((value) => Math.min(value + 1, 2))
  return <div className="entry-shell"><div className="entry-brand"><span className="brand-mark">ø</span><strong>Zerøbyte</strong><small>Business</small></div><div className="entry-grid"><div className="entry-copy"><p className="eyebrow">A clearer way to operate</p><h1>Run the work.<br /><em>Keep the signal.</em></h1><p>One calm workspace for the details that keep your business moving.</p><div className="entry-proof"><span><Check size={14} /> Inventory clarity</span><span><Check size={14} /> Sales in context</span><span><Check size={14} /> Organization-first data</span></div></div><div className="entry-card">{mode === 'welcome' && <><div className="entry-icon"><ShieldCheck size={18} /></div><h2>Welcome to Zerøbyte</h2><p>Start with a focused workspace for your daily operations.</p><button className="primary entry-button" onClick={() => { window.location.pathname = '/auth' }}>Create a workspace <ArrowRight size={16} /></button><button className="entry-link" onClick={() => { window.location.pathname = '/' }}>Explore the product</button></>}{mode === 'auth' && <><div className="entry-icon"><LockKeyhole size={18} /></div><h2>Sign in to your workspace</h2><p>Use your work email to continue. No payment details required.</p><label>Email address<input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@company.com" type="email" /></label><button className="primary entry-button" disabled={!email.includes('@')} onClick={() => { window.location.pathname = '/onboarding' }}>Continue <ArrowRight size={16} /></button><button className="entry-link" onClick={() => { window.location.pathname = '/welcome' }}>Back to welcome</button></>}{mode === 'onboarding' && <><div className="stepper">{[0, 1, 2].map((item) => <span className={item <= step ? 'done' : ''} key={item}>{item + 1}</span>)}</div><h2>{step === 0 ? 'Name your workspace' : step === 1 ? 'Choose your focus' : 'You’re ready to go'}</h2><p>{step === 0 ? 'This is where your team will work together.' : step === 1 ? 'We’ll shape your starting view around the work you do most.' : 'Your workspace will use real, organization-scoped records.'}</p>{step === 0 && <input placeholder="e.g. Adebayo Foods" />}{step === 1 && <div className="choice-list"><button className="choice active">Retail & products <Check size={15} /></button><button className="choice">Services & projects</button></div>}{step < 2 ? <button className="primary entry-button" onClick={next}>Continue <ArrowRight size={16} /></button> : <button className="primary entry-button" onClick={() => { window.location.pathname = '/' }}>Open workspace <ArrowRight size={16} /></button>}</>}</div></div><footer>Built for independent teams · <span>Privacy by design</span></footer></div>
}
